version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apivendas-api
    port: 
      -"3333:3333"
    
    volumes:
      - .:/home/node/app
    
    dependes_on:
      - db
      - redis
  
  db:
    build: .docker/postgres
    container_name: apivendas-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes: 
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apivendas
  
  redis:
    image: 'bitnami/redis:latest'
    container_name: apivendas-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes